server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 


zuul:
  #访问地址前缀
  prefix: /atguigu
  #关闭真实入口，配置之后只能通过虚拟地址访问
  #ignored-services: microservicecloud-dept
  ignored-services: "*"
  #虚拟地址配置   http://myzuul.com:9527/microservicecloud-dept/dept/get/1 --》http://myzuul.com:9527/mydept/dept/get/1
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
 
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

